# Setup
title:               Math 106
tagline:             'Stochastic processes'
description:         'A course on stochastic processes and their applications.'
url: "https://elevien.github.io"   # no trailing slash
baseurl: "/math106" 
permalink:           pretty

# About/contact
author:
  name:              Ethan Levien
  email:             ethanlevien@gmail.com


# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag



# # Custom vars
# version:             1.1.0
# google_analytics_id: #UA-XXXX-Y
